# Generated by Django 2.0.7 on 2018-07-12 09:25

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0004_triviafeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=255)),
                ('point', django.contrib.gis.db.models.fields.PointField(help_text='WGS 84 latitude/longitude where stop was placed', srid=4326)),
                ('position_correct', models.CharField(blank=True, choices=[('0', 'Skip'), ('1', 'Correct'), ('2', 'False')], help_text='Is this position accurate??', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
