# Generated by Django 2.0.7 on 2018-07-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_transitfeedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transitfeedback',
            options={'verbose_name': 'Transit feedback', 'verbose_name_plural': 'Transit feedback'},
        ),
        migrations.AlterModelOptions(
            name='triviafeedback',
            options={'verbose_name': 'Trivia feedback', 'verbose_name_plural': 'Trivia feedback'},
        ),
    ]
