# Generated by Django 2.0.7 on 2018-09-13 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_to', models.CharField(blank=True, max_length=255, null=True)),
                ('stop_from', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('stop_from_id', models.CharField(blank=True, max_length=255, null=True)),
                ('route_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stop_to_id', models.CharField(blank=True, max_length=255, null=True)),
                ('weather', models.CharField(blank=True, max_length=255, null=True)),
                ('traffic_jam', models.CharField(blank=True, max_length=255, null=True)),
                ('demand', models.CharField(blank=True, max_length=255, null=True)),
                ('air_quality', models.CharField(blank=True, max_length=255, null=True)),
                ('peak', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_time', models.CharField(blank=True, max_length=255, null=True)),
                ('crowd', models.CharField(blank=True, max_length=255, null=True)),
                ('safety', models.CharField(blank=True, max_length=255, null=True)),
                ('drive_safety', models.CharField(blank=True, max_length=255, null=True)),
                ('music', models.CharField(blank=True, max_length=255, null=True)),
                ('internet', models.CharField(blank=True, max_length=255, null=True)),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
